server:
  port: 8003

spring:
  application:
    name: authserver
  config:
    import: "optional:configserver:"
    config:
      uri: http://${CONFIG_HOSTNAME:localhost}:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true  TODO mock config for tests
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      lifecycle:
        timeout-per-shutdown-phase: 15s